M48
; DRILL file {KiCad 9.0.6} date 2026-03-13T11:42:13-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-03-13T11:42:13-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X76.823Y-135.27
X81.673Y-135.27
T2
X76.523Y-138.3
X81.973Y-138.3
M30
